name: activity-prediction-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - matplotlib=3.4.1
  - numpy=1.20.2
  - pandas=1.2.4
  - rdkit=2021.03.1
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - shap=0.39.0
  - seaborn=0.11.1
